---
- hosts: centosserver
  become: true
  tasks:
    - name: Ensure firewalld is installed and running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open HTTP (port 80) in the firewall
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open HTTPS (port 443) in the firewall
      ansible.posix.firewalld:
        service: https
        permanent: yes
        state: enabled
        immediate: yes

