---
- hosts: centosserver
  become: true
  tasks:

    - name: install httpd  and Mariadb packages
      ansible.builtin.dnf:
        name:
          - httpd
          - mariadb-server
        state: present

    - name: Ensure httpd server is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Ensure MariaDB is started and enabled
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true
